### ISSUE TITLE
domain is hardcoded, leading folks to a provision error

### ISSUE THREAD

**Issue by vhvb1989** [pamelafox/pamelafox-site#17]
Domain value in `main.parameters.json` is hardcoded to 

```json
    "domainName": {
      "value": "www.pamelafox.org"
    }
```

While provisioning, the next error is shown:

![image](https://user-images.githubusercontent.com/24213737/231901279-7a3cb67f-b0da-4964-8c68-89c2836a86b9.png)

You might want to make this configuration optional, or provide notes in the Readme about it to be changed or disabled

**Comment by vhvb1989** [comment]
Note that the environment name is also set to 

`"value": "pamelafox-swa"`

This makes azd to create resources using this prefix

**Comment by pamelafox** [comment]
Oh yeah, thats because this is just my personal site. I have a fork of this that I'm trying to make more generically useful for the AZD templates gallery, but am working out issues on this one first. But perhaps I could just make this one really generic too, easier than maintaining the fork. Hmm.

**Comment by vhvb1989** [comment]
makes sense. thank you
